import type { Metadata } from "next";
import "./globals.css";

import { montserrat_normal } from "@/app/ui/fonts";
import Sidebar from "@/app/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat_normal.className}>
        <Sidebar />
        <div>{children}</div>
      </body>
    </html>
  );
}
